### ISSUE TITLE
Error occurred when executing MagicClothing_Generate

### ISSUE THREAD

**Issue by Correiae** [frankchieng/ComfyUI_MagicClothing#12]
Hi, 
how can I fix this error ?

Error occurred when executing MagicClothing_Generate:

int() argument must be a string, a bytes-like object or a real number, not 'Image'

File "E:\Ai_test\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\Ai_test\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\Ai_test\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\Ai_test\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 179, in garment_generation
images = np.array(images).astype(np.float32) / 255.0

**Comment by m-deepankar-singh** [comment]
same here

**Comment by shangshangdyx** [comment]
same here

**Comment by frankchieng** [comment]
you can install this project thr [ComfyUI-Manager](https://github.com/ltdrdata/ComfyUI-Manager) as well, i just tested in Windows10 system, it run well 
![1713585688650](https://github.com/frankchieng/ComfyUI_MagicClothing/assets/130369523/eef7f4b4-c3bf-4003-a9af-58152c9bd03e)

**Comment by shangshangdyx** [comment]
电脑系统：win11
插件安装：从ComfyUI-Manager
后台报错：
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.16it/s]
----checkpoints loaded from path: E:\ComfyUI\custom_nodes\ComfyUI_MagicClothing\checkpoints\cloth_segm.pth----
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.25it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 179, in garment_generation
    images = np.array(images).astype(np.float32) / 255.0
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Image'

Prompt executed in 5.77 seconds
<img width="1021" alt="微信图片_20240420123140" src="https://github.com/frankchieng/ComfyUI_MagicClothing/assets/25240937/3bb706fc-c008-47a4-8276-4047e58ab71e">

**Comment by frankchieng** [comment]
try git pull and update ComfyUI

**Comment by shangshangdyx** [comment]
I am trying git pull and update, it still not working, the same wrong

**Comment by frankchieng** [comment]
you should check you numpy version, numpy>=1.25.1 double check all the library in requirements.txt

**Comment by m-deepankar-singh** [comment]
> you should check you numpy version, numpy>=1.25.1 double check all the library in requirements.txt

this fixed it thanks

**Comment by AB00k** [comment]
@Correiae I'm still having this error, have you resolved this error

**Comment by Correiae** [comment]
> @Correiae I'm still having this error, have you resolved this error

Yes after a fresh re install of Comfy, but I've got another errors when I use the other worflows :(

**Comment by AB00k** [comment]
@Correiae what are those other errors, I'm actually re installing the whole environment (actually I'm using on colab) so I'll see if this error is resolved or not.

**Comment by AB00k** [comment]
I'm still having following error
/usr/local/lib/python3.10/dist-packages/diffusers/loaders/lora.py:1078: FutureWarning: `fuse_text_encoder_lora` is deprecated and will be removed in version 0.27. You are using an old version of LoRA backend. This will be deprecated in the next releases in favor of PEFT make sure to install the latest PEFT and transformers packages in the future.
  deprecate("fuse_text_encoder_lora", "0.27", LORA_DEPRECATION_MESSAGE)
!!! Exception during processing!!! expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/ComfyUI/custom_nodes/ComfyUI_MagicClothing/nodes.py", line 268, in garment_generation
    ip_model = IPAdapterFaceID(pipe, folder_paths.get_full_path("magic_cloth_checkpoint", model_path), ip_ckpt, device, enable_cloth_guidance)
  File "/content/ComfyUI/custom_nodes/ComfyUI_MagicClothing/garment_adapter/garment_ipadapter_faceid.py", line 134, in __init__
    self.load_ip_adapter()
  File "/content/ComfyUI/custom_nodes/ComfyUI_MagicClothing/garment_adapter/garment_ipadapter_faceid.py", line 198, in load_ip_adapter
    if os.path.splitext(self.ip_ckpt)[-1] == ".safetensors":
  File "/usr/lib/python3.10/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Tugpsx** [comment]
Can run garment only but when adding any other options get a similar error:

Error occurred when executing MagicClothing_Generate:

expected str, bytes or os.PathLike object, not NoneType

File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 285, in garment_generation
ip_model = IPAdapterFaceID(pipe, folder_paths.get_full_path("magic_cloth_checkpoint", model_path), image_encoder_path, ip_ckpt, device, enable_cloth_guidance)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\garment_adapter\garment_ipadapter_faceid.py", line 341, in __init__
self.load_ip_adapter()
File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\garment_adapter\garment_ipadapter_faceid.py", line 406, in load_ip_adapter
if os.path.splitext(self.ip_ckpt)[-1] == ".safetensors":
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 232, in splitext

**Comment by Tugpsx** [comment]
![Screenshot 2024-05-04 130317](https://github.com/frankchieng/ComfyUI_MagicClothing/assets/109868388/acd81d5b-eefd-43c4-a53a-ad10925ae27d)

**Comment by SajivGen** [comment]
Error occurred when executing MagicClothing_Generate:

[Errno 2] No such file or directory: 'C:\\Users\\Sajiv\\.cache\\huggingface\\hub\\models--stabilityai--sd-vae-ft-mse\\snapshots\\31f26fdeee1355a5c34592e401dd41e45d25a493\\config.json'

File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 192, in garment_generation
vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse").to(dtype=torch.float16)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 569, in from_pretrained
config, unused_kwargs, commit_hash = cls.load_config(
^^^^^^^^^^^^^^^^
File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 428, in load_config
config_dict = cls._dict_from_json_file(config_file)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Sajiv\Documents\Image Generation\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 549, in _dict_from_json_file
with open(json_file, "r", encoding="utf-8") as reader:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by 2498900677** [comment]
Error occurred when executing MagicClothing_Generate:

(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/SG161222/Realistic_Vision_V4.0_noVAE (Caused by ConnectTimeoutError(, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: fdf8ce5c-b8c5-498a-b763-1e0e4c02b2a9)')

File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 298, in garment_generation
pipe = StableDiffusionPipeline.from_pretrained(pipe_path, vae=vae, torch_dtype=torch.float16)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1096, in from_pretrained
cached_folder = cls.download(
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1656, in download
info = model_info(pretrained_model_name, token=token, revision=revision)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\hf_api.py", line 2084, in model_info
r = get_session().get(path, headers=headers, timeout=timeout, params=params)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 602, in get
return self.request("GET", url, **kwargs)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
return super().send(request, *args, **kwargs)
File "G:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\requests\adapters.py", line 507, in send
raise ConnectTimeout(e, request=request)
![0012](https://github.com/user-attachments/assets/271c81ff-467a-42a0-bb4d-893cc1e4c46a)
