### ISSUE TITLE
with simple workflow

### ISSUE THREAD

**Issue by zachysaur** [frankchieng/ComfyUI_MagicClothing#2]
got prompt
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:16<00:00,  3.31s/it]
----checkpoints loaded from path: F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\checkpoints\cloth_segm.pth----
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 177, in garment_generation
    images, cloth_mask_image = full_net.generate(cloth_image, cloth_mask_image, prompt, a_prompt, num_samples, n_prompt, seed, scale, cloth_guidance_scale, sample_steps, height, width)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\garment_adapter\garment_diffusion.py", line 96, in generate
    images = self.pipe(
             ^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\pipelines\OmsDiffusionPipeline.py", line 221, in __call__
    if self.interrupt:
       ^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 138, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OmsDiffusionPipeline' object has no attribute 'interrupt'

Prompt executed in 179.08 seconds

**Comment by frankchieng** [comment]
> got prompt Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:16<00:00, 3.31s/it] ----checkpoints loaded from path: F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\checkpoints\cloth_segm.pth---- 0%| | 0/20 [00:00<?, ?it/s] ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last): File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 177, in garment_generation images, cloth_mask_image = full_net.generate(cloth_image, cloth_mask_image, prompt, a_prompt, num_samples, n_prompt, seed, scale, cloth_guidance_scale, sample_steps, height, width) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\garment_adapter\garment_diffusion.py", line 96, in generate images = self.pipe( ^^^^^^^^^^ File "F:\UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\pipelines\OmsDiffusionPipeline.py", line 221, in **call** if self.interrupt: ^^^^^^^^^^^^^^ File "F:\UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 138, in **getattr** raise AttributeError(f"'{type(self).**name**}' object has no attribute '{name}'") AttributeError: 'OmsDiffusionPipeline' object has no attribute 'interrupt'
> 
> Prompt executed in 179.08 seconds

check your local diffusers version and be match in the requirements.txt
