### ISSUE TITLE
Error occurred when executing MagicClothing_Generate:  stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by TAYLENHE** [frankchieng/ComfyUI_MagicClothing#24]
what is "Error occurred when executing MagicClothing_Generate:

stat: path should be string, bytes, os.PathLike or integer, not NoneType
"

**Comment by oracle9i88** [comment]
+1

**Comment by JosephThomasParker** [comment]
Had this too. I got past it by putting `cloth_segm.pth` from https://huggingface.co/ShineChen1024/MagicClothing/tree/main into `custom_nodes/ComfyUI_MagicClothing/checkpoints/`.

**Comment by zachysaur** [comment]
same error

**Comment by oracle9i88** [comment]
> Had this too. I got past it by putting `cloth_segm.pth` from https://huggingface.co/ShineChen1024/MagicClothing/tree/main into `custom_nodes/ComfyUI_MagicClothing/checkpoints/`.也有这个。我通过将 https://huggingface.co/ShineChen1024/MagicClothing/tree/main 中的 `cloth_segm.pth` 放入 `custom_nodes/ComfyUI_MagicClothing/checkpoints/` 来克服它。

not work

**Comment by MoonMoon82** [comment]
Same issue here:

```
!!! Exception during processing!!! stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 264, in garment_generation
    pipe.load_lora_weights(ip_lora)
  File "E:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\lora.py", line 110, in load_lora_weights
    state_dict, network_alphas = self.lora_state_dict(pretrained_model_name_or_path_or_dict, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\lora.py", line 236, in lora_state_dict
    weight_name = cls._best_guess_weight_name(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\lora.py", line 312, in _best_guess_weight_name
    if os.path.isfile(pretrained_model_name_or_path_or_dict):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Prompt executed in 4.05 seconds
```

If there is a file missing, this error message gives no hint what file it might be.

**Comment by samen168** [comment]
+1

**Comment by fsdymy1024** [comment]
代码faceid 模型、lora写死了，路径、文件名需要跟代码对应上
![image](https://github.com/frankchieng/ComfyUI_MagicClothing/assets/40141832/5873eb3e-13bf-4593-8c77-962429389bcc)

**Comment by foanfan-qq** [comment]
这个问题有人解决了，网上都搜不到解决办法
