### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by zachysaur** [frankchieng/ComfyUI_MagicClothing#4]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 92, in garment_generation
    result = ip_model.generate(cloth_image, face_image, cloth_mask_image, prompt, a_prompt, n_prompt, num_samples, seed, scale, cloth_guidance_scale, sample_steps, height, width)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\garment_adapter\garment_ipadapter_faceid.py", line 306, in generate
    images = self.pipe(
             ^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing\pipelines\OmsDiffusionPipeline.py", line 221, in __call__
    if self.interrupt:
       ^^^^^^^^^^^^^^
  File "F:\UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 138, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OmsDiffusionPipeline' object has no attribute 'interrupt'

Prompt executed in 77.53 seconds

**Comment by frankchieng** [comment]
check your local diffusers version and be match in the requirements.txt

**Comment by zachysaur** [comment]
how?
