### ISSUE TITLE
SG161222/Realistic_Vision_V4.0_noVAE

### ISSUE THREAD

**Issue by carlvane1211** [frankchieng/ComfyUI_MagicClothing#47]
Realistic_Vision_V4.0_noVAE 
I have downloaded this plugin, but where do I put it? Or what plugin do I need to install?

got prompt
Couldn't connect to the Hub: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/SG161222/Realistic_Vision_V4.0_noVAE (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002724F139790>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 782af8fc-8857-4e65-b61b-433a8c550edc)').
Will try to load from local cache.
!!! Exception during processing!!! stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\custom_nodes\ComfyUI_MagicClothing\nodes.py", line 211, in garment_generation
    pipe.load_lora_weights(ip_lora)
  File "D:\ComfyUI_windows_portable\.ext\Lib\site-packages\diffusers\loaders\lora.py", line 110, in load_lora_weights
    state_dict, network_alphas = self.lora_state_dict(pretrained_model_name_or_path_or_dict, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\.ext\Lib\site-packages\diffusers\loaders\lora.py", line 236, in lora_state_dict
    weight_name = cls._best_guess_weight_name(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\.ext\Lib\site-packages\diffusers\loaders\lora.py", line 312, in _best_guess_weight_name
    if os.path.isfile(pretrained_model_name_or_path_or_dict):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Prompt executed in 78.19 seconds

**Comment by frankchieng** [comment]
the model will be downloaded in the hunggingface cache directory,you can change the default directory thr env HF_HOME

**Comment by alexgenovese** [comment]
@frankchieng, can I suggest removing this feature and replacing it with a list of all models available in the **models/checkpoints** folder?

**Comment by Amit30swgoh** [comment]
yes because we cant use it either way please fix it

**Comment by yatoubusha** [comment]
> the model will be downloaded in the hunggingface cache directory,you can change the default directory thr env HF_HOME

If I manually download these files, where can I put them to be loaded correctly?
