### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Image'

### ISSUE THREAD

**Issue by Kevin-coder80** [frankchieng/ComfyUI_MagicClothing#53]
Getting this error with generation.

`----checkpoints loaded from path: /home/xxxx/ai/ComfyUI/custom_nodes/ComfyUI_MagicClothing/checkpoints/cloth_segm.pth----
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.06it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/home/liuwei/ai/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuwei/ai/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuwei/ai/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuwei/ai/ComfyUI/custom_nodes/ComfyUI_MagicClothing/nodes.py", line 303, in garment_generation
    images = np.array(images).astype(np.float32) / 255.0
             ^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Image'

Prompt executed in 32.89 seconds
`
![image](https://github.com/frankchieng/ComfyUI_MagicClothing/assets/2867973/7b163bfa-e392-4193-ab40-7ec464d25812)

**Comment by frankchieng** [comment]
you should check out the workflow files in the assets directory,especially the ipadapter_faceid_workflow.json (Garment Generation Sampler) node is different from the magic_clothing_workflow.json

**Comment by Liya2199** [comment]
line 307 in node.py: modify **images = np.array(images).astype(np.float32) / 255.0** to **if isinstance(images, list):
            images = [np.array(img).astype(np.float32) / 255.0 for img in images]
            images = np.stack(images, axis=0) 
        else:
            images = np.array(images).astype(np.float32) / 255.0** 
maybe it's useful

**Comment by thor9king** [comment]
@Liya2199 it's work for me, thx!

**Comment by 2498900677** [comment]
Please, is the problem solved? So the problem is solved
