### ISSUE TITLE
AttributeError: 'OmsAnimateDiffusionPipeline' object has no attribute '_retrieve_video_frames'

### ISSUE THREAD

**Issue by brightming** [frankchieng/ComfyUI_MagicClothing#64]
at the last step , encount this error:
anyone knows how to solve it ? thanks! 

----checkpoints loaded from path: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing-main\checkpoints\cloth_segm.pth----
UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:52<00:00,  2.64s/it]
!!! Exception during processing!!! 'OmsAnimateDiffusionPipeline' object has no attribute '_retrieve_video_frames'
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing-main\nodes.py", line 151, in animatediff_generation
    frames, cloth_mask_image = full_net.generate(cloth_image, cloth_mask_image, kwargs['prompt'], a_prompt, kwargs['num_images_per_prompt'], kwargs['negative_prompt'], kwargs['seed'], kwargs['guidance_scale'], kwargs['cloth_guidance_scale'], kwargs['sample_steps'], kwargs['height'], kwargs['width'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing-main\garment_adapter\garment_diffusion.py", line 263, in generate
    frames = self.pipe(
             ^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MagicClothing-main\pipelines\OmsAnimateDiffusionPipeline.py", line 301, in __call__
    video = self._retrieve_video_frames(latents, output_type, return_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 143, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OmsAnimateDiffusionPipeline' object has no attribute '_retrieve_video_frames'

**Comment by leandrotorrent-marvik** [comment]
any solution for this issue?

**Comment by frankchieng** [comment]
you'd better downgrade diffusers version to 0.26.2 which corresponding to requirements.txt
