### ISSUE TITLE
For single controlnet: `controlnet_conditioning_scale` must be type `float`.

### ISSUE THREAD

**Issue by yatoubusha** [frankchieng/ComfyUI_MagicClothing#75]
i print the type and value of controlnet_conditioning_scale before self.check_inputs, it is float tyle and the value equals 1.0, while the code still return this error? Is it possible that there is an issue with the version of the diffusers library?
![image](https://github.com/user-attachments/assets/d3fed443-3407-43f7-bd98-79620704c693)

**Comment by judithdrive** [comment]
same here

**Comment by jh248** [comment]
same here

**Comment by frankchieng** [comment]
there are two methods this issue can be resolved.First,you can downgrade the diffusers version corresponding to diffusers==0.26.2 in the requirements.txt. Second,if you upgrade diffusers to updated version like 0.30.3, you should modify the code of 
```
self.check_inputs(
            prompt,
            image,
            callback_steps,
            negative_prompt,
            prompt_embeds,
            negative_prompt_embeds,
            controlnet_conditioning_scale,
            control_guidance_start,
            control_guidance_end,
            callback_on_step_end_tensor_inputs,
        )
```
located in pipelines/OmsDiffusionControlNetPipeline.py as below
``` 
self.check_inputs(
            prompt,
            image,
            callback_steps,
            negative_prompt,
            prompt_embeds,
            negative_prompt_embeds,
            controlnet_conditioning_scale=controlnet_conditioning_scale,
            control_guidance_start=control_guidance_start,
            control_guidance_end=control_guidance_end,
            callback_on_step_end_tensor_inputs=callback_on_step_end_tensor_inputs,
        )
```

**Comment by goedzo** [comment]
I run into the same issue and tried to update pipelines/OmsDiffusionControlNetPipeline.py as suggested, but still get this error:

!!! Exception during processing !!! For single controlnet: `controlnet_conditioning_scale` must be type `float`.
Traceback (most recent call last):
  File "V:\AIVideogenerator\ComfyUI_windows_portable\ComfyUI\execution.py", line 361, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\AIVideogenerator\ComfyUI_windows_portable\ComfyUI\execution.py", line 236, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\AIVideogenerator\ComfyUI_windows_portable\ComfyUI\execution.py", line 208, in _map_node_over_list
    process_inputs(input_dict, i)
  File "V:\AIVideogenerator\ComfyUI_windows_portable\ComfyUI\execution.py", line 197, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\AIVideogenerator\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_magicclothing\nodes.py", line 103, in cloth_inpainting
    images, cloth_mask_image = full_net.generate(cloth_image, cloth_mask_image, kwargs['prompt'], a_prompt, kwargs['num_samples'], kwargs['negative_prompt'], kwargs['seed'], kwargs['guidance_scale'], kwargs['cloth_guidance_scale'], kwargs['sample_steps'], kwargs['height'], kwargs['width'], image=person_image,mask_image=person_mask,control_image=control_img)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\AIVideogenerator\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_magicclothing\garment_adapter\garment_diffusion.py", line 96, in generate
    images = self.pipe(
             ^^^^^^^^^^
  File "V:\AIVideogenerator\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "V:\AIVideogenerator\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_magicclothing\pipelines\VirtualTryOnPipeline.py", line 189, in __call__
    self.check_inputs(
  File "V:\AIVideogenerator\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\pipelines\controlnet\pipeline_controlnet_inpaint.py", line 718, in check_inputs
    raise TypeError("For single controlnet: `controlnet_conditioning_scale` must be type `float`.")
TypeError: For single controlnet: `controlnet_conditioning_scale` must be type `float`.

**Comment by goedzo** [comment]
Ok I was also able to get rid of the error by updating VirtualTryOnPipeline.py to:

        self.check_inputs(
            prompt,
            control_image,
            mask_image,
            height,
            width,
            callback_steps,
            output_type,
            negative_prompt,
            prompt_embeds,
            negative_prompt_embeds,
            controlnet_conditioning_scale=controlnet_conditioning_scale,
            control_guidance_start=control_guidance_start,
            control_guidance_end=control_guidance_end,
            callback_on_step_end_tensor_inputs=callback_on_step_end_tensor_inputs,
            padding_mask_crop=padding_mask_crop,
        )
