### ISSUE TITLE
类型不匹配

### ISSUE THREAD

**Issue by jh248** [frankchieng/ComfyUI_MagicClothing#78]
# ComfyUI Error Report
## Error Details
- **Node Type:** MagicClothing_Inpainting
- **Exception Type:** TypeError
- **Exception Message:** For single controlnet: `controlnet_conditioning_scale` must be type `float`.
## Stack Trace
```
  File "/home/runner/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/runner/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_MagicClothing/nodes.py", line 103, in cloth_inpainting
    images, cloth_mask_image = full_net.generate(cloth_image, cloth_mask_image, kwargs['prompt'], a_prompt, kwargs['num_samples'], kwargs['negative_prompt'], kwargs['seed'], kwargs['guidance_scale'], kwargs['cloth_guidance_scale'], kwargs['sample_steps'], kwargs['height'], kwargs['width'], image=person_image,mask_image=person_mask,control_image=control_img)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_MagicClothing/garment_adapter/garment_diffusion.py", line 96, in generate
    images = self.pipe(
             ^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_MagicClothing/pipelines/VirtualTryOnPipeline.py", line 189, in __call__
    self.check_inputs(

  File "/usr/local/lib/python3.11/dist-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py", line 704, in check_inputs
    raise TypeError("For single controlnet: `controlnet_conditioning_scale` must be type `float`.")

```
## System Information
- **ComfyUI Version:** v0.2.2-1-gc27ebeb
- **Arguments:** ComfyUI/main.py --port 7860 --listen --disable-xformers
- **OS:** posix
- **Python Version:** 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25430786048
  - **VRAM Free:** 24155717632
  - **Torch VRAM Total:** 67108864
  - **Torch VRAM Free:** 33554432

## Logs
```
2024-10-07 22:40:38,637 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-07 22:40:38,637 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-10-07 22:40:39,561 - root - INFO - Using pytorch cross attention
2024-10-07 22:40:40,430 - root - INFO - [Prompt Server] web root: /home/runner/ComfyUI/web
2024-10-07 22:40:42,692 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-3D-Pack/__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 37, in <module>
    from .mesh_processer.mesh import Mesh
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-3D-Pack/mesh_processer/mesh.py", line 8, in <module>
    from kiui.op import safe_normalize, dot
ModuleNotFoundError: No module named 'kiui'

2024-10-07 22:40:42,692 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-3D-Pack module for custom nodes: No module named 'kiui'
2024-10-07 22:41:24,756 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-Anyline/__init__.py", line 1, in <module>
    from .anyline import AnyLine
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-Anyline/anyline.py", line 9, in <module>
    from custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed import TEDDetector
ImportError: cannot import name 'TEDDetector' from 'custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed' (unknown location)

2024-10-07 22:41:24,756 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-Anyline module for custom nodes: cannot import name 'TEDDetector' from 'custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed' (unknown location)
2024-10-07 22:41:25,236 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-Background-Replacement/__init__.py", line 8, in <module>
    from .background_replacement import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-Background-Replacement/background_replacement.py", line 11, in <module>
    from .image_utils import ensure_resolution
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-Background-Replacement/image_utils.py", line 4, in <module>
    from .upscaler import upscale
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-Background-Replacement/upscaler.py", line 4, in <module>
    from realesrgan import RealESRGANer
  File "/usr/local/lib/python3.11/dist-packages/realesrgan/__init__.py", line 2, in <module>
    from .archs import *
  File "/usr/local/lib/python3.11/dist-packages/realesrgan/archs/__init__.py", line 2, in <module>
    from basicsr.utils import scandir
  File "/usr/local/lib/python3.11/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.11/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.11/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

2024-10-07 22:41:25,236 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-Background-Replacement module for custom nodes: No module named 'torchvision.transforms.functional_tensor'
2024-10-07 22:41:25,264 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-BrushNet-Wrapper/nodes.py", line 18, in <module>
    from diffusers.loaders.single_file_utils import (
ImportError: cannot import name 'create_vae_diffusers_config' from 'diffusers.loaders.single_file_utils' (/usr/local/lib/python3.11/dist-packages/diffusers/loaders/single_file_utils.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-BrushNet-Wrapper/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-BrushNet-Wrapper/nodes.py", line 26, in <module>
    raise ImportError("Diffusers version too old. Please update to 0.27.2 minimum.")
ImportError: Diffusers version too old. Please update to 0.27.2 minimum.

2024-10-07 22:41:25,264 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-BrushNet-Wrapper module for custom nodes: Diffusers version too old. Please update to 0.27.2 minimum.
2024-10-07 22:41:29,216 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-DepthFM/__init__.py", line 1, in <module>
    from . import DepthFM
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-DepthFM/DepthFM.py", line 6, in <module>
    from .depthfm import DepthFM
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-DepthFM/depthfm/__init__.py", line 4, in <module>
    from dfm import DepthFM
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-DepthFM/depthfm/dfm.py", line 9, in <module>
    from unet import UNetModel
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-DepthFM/depthfm/unet/__init__.py", line 4, in <module>
    from openaimodel import UNetModel
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-DepthFM/depthfm/unet/openaimodel.py", line 8, in <module>
    from util import (
ImportError: cannot import name 'checkpoint' from 'util' (/home/runner/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_controlnet_aux/util.py)

2024-10-07 22:41:29,217 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-DepthFM module for custom nodes: cannot import name 'checkpoint' from 'util' (/home/runner/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_controlnet_aux/util.py)
2024-10-07 22:41:29,230 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-ELLA-wrapper/nodes.py", line 20, in <module>
    from diffusers.loaders.single_file_utils import (
ImportError: cannot import name 'create_vae_diffusers_config' from 'diffusers.loaders.single_file_utils' (/usr/local/lib/python3.11/dist-packages/diffusers/loaders/single_file_utils.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-ELLA-wrapper/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-ELLA-wrapper/nodes.py", line 28, in <module>
    raise ImportError("Diffusers version too old. Please update to 0.26.0 minimum.")
ImportError: Diffusers version too old. Please update to 0.26.0 minimum.

2024-10-07 22:41:29,230 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-ELLA-wrapper module for custom nodes: Diffusers version too old. Please update to 0.26.0 minimum.
2024-10-07 22:41:29,638 - root - INFO - Total VRAM 24253 MB, total RAM 193302 MB
2024-10-07 22:41:29,638 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-07 22:41:29,639 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-07 22:41:29,639 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-10-07 22:41:29,645 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-IC-Light-Wrapper/nodes.py", line 19, in <module>
    from diffusers.loaders.single_file_utils import (
ImportError: cannot import name 'create_vae_diffusers_config' from 'diffusers.loaders.single_file_utils' (/usr/local/lib/python3.11/dist-packages/diffusers/loaders/single_file_utils.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-IC-Light-Wrapper/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-IC-Light-Wrapper/nodes.py", line 27, in <module>
    raise ImportError("Diffusers version too old. Please update to 0.26.0 minimum.")
ImportError: Diffusers version too old. Please update to 0.26.0 minimum.

2024-10-07 22:41:29,645 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-IC-Light-Wrapper module for custom nodes: Diffusers version too old. Please update to 0.26.0 minimum.
2024-10-07 22:41:29,650 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-IDM-VTON/__init__.py", line 2, in <module>
    from .src.nodes_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-IDM-VTON/src/nodes_mappings.py", line 1, in <module>
    from .nodes.pipeline_loader import PipelineLoader
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-IDM-VTON/src/nodes/pipeline_loader.py", line 9, in <module>
    from ..idm_vton.unet_hacked_tryon import UNet2DConditionModel
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-IDM-VTON/src/idm_vton/unet_hacked_tryon.py", line 50, in <module>
    from .unet_block_hacked_tryon import (
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-IDM-VTON/src/idm_vton/unet_block_hacked_tryon.py", line 25, in <module>
    from diffusers.models.dual_transformer_2d import DualTransformer2DModel
ModuleNotFoundError: No module named 'diffusers.models.dual_transformer_2d'

2024-10-07 22:41:29,651 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-IDM-VTON module for custom nodes: No module named 'diffusers.models.dual_transformer_2d'
2024-10-07 22:41:32,764 - albumentations.check_version - INFO - A new version of Albumentations is available: 1.4.17 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations
2024-10-07 22:41:44,784 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/LCM_Inpaint-Outpaint_Comfy/__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "/home/runner/ComfyUI/custom_nodes/LCM_Inpaint-Outpaint_Comfy/LCM_Nodes.py", line 9, in <module>
    from .LCM.LCM_reference_pipeline import LatentConsistencyModelPipeline_reference
  File "/home/runner/ComfyUI/custom_nodes/LCM_Inpaint-Outpaint_Comfy/LCM/LCM_reference_pipeline.py", line 33, in <module>
    from diffusers.models.unet_2d_blocks import CrossAttnDownBlock2D, CrossAttnUpBlock2D, DownBlock2D, UpBlock2D
ModuleNotFoundError: No module named 'diffusers.models.unet_2d_blocks'

2024-10-07 22:41:44,784 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/LCM_Inpaint-Outpaint_Comfy module for custom nodes: No module named 'diffusers.models.unet_2d_blocks'
2024-10-07 22:41:45,715 - root - INFO - --------------
2024-10-07 22:41:45,715 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-10-07 22:41:45,715 - root - INFO - ChatGPT.available True
2024-10-07 22:41:45,715 - root - INFO - edit_mask.available True
2024-10-07 22:41:45,718 - root - INFO - LaMaInpainting.available True
2024-10-07 22:41:45,734 - root - INFO - ClipInterrogator.available True
2024-10-07 22:41:45,734 - root - INFO - PromptGenerate.available True
2024-10-07 22:41:45,735 - root - INFO - ChinesePrompt.available True
2024-10-07 22:41:45,735 - root - INFO - RembgNode_.available True
2024-10-07 22:41:45,738 - root - INFO - TripoSR.available
2024-10-07 22:41:45,739 - root - INFO - MiniCPMNode.available
2024-10-07 22:41:45,739 - root - INFO - [93m -------------- [0m
2024-10-07 22:41:45,916 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/ComfyUI/custom_nodes/scatter/__init__.py'

2024-10-07 22:41:45,916 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/scatter module for custom nodes: [Errno 2] No such file or directory: '/home/runner/ComfyUI/custom_nodes/scatter/__init__.py'
2024-10-07 22:41:47,380 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/ComfyUI/custom_nodes/xformers/__init__.py'

2024-10-07 22:41:47,380 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/xformers module for custom nodes: [Errno 2] No such file or directory: '/home/runner/ComfyUI/custom_nodes/xformers/__init__.py'
2024-10-07 22:41:48,874 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-OpenDIT/__init__.py", line 3, in <module>
    from .dit_nodes import *
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-OpenDIT/dit_nodes.py", line 27, in <module>
    from opendit.models.opensora_plan import LatteT2V as OpensoraPlanLatteT2V,getae_wrapper,ae_stride_config,VideoGenPipeline
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-OpenDIT/opendit/models/opensora_plan/__init__.py", line 2, in <module>
    from .latte import LatteT2V
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-OpenDIT/opendit/models/opensora_plan/latte.py", line 22, in <module>
    from diffusers.models.attention_processor import (
ImportError: cannot import name 'LORA_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor' (/usr/local/lib/python3.11/dist-packages/diffusers/models/attention_processor.py)

2024-10-07 22:41:48,874 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-OpenDIT module for custom nodes: cannot import name 'LORA_ATTENTION_PROCESSORS' from 'diffusers.models.attention_processor' (/usr/local/lib/python3.11/dist-packages/diffusers/models/attention_processor.py)
2024-10-07 22:41:48,884 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-ViViD/__init__.py", line 27, in <module>
    from .nodes import LoadVideo,PreViewVideo,LoadImagePath,ViViD_Node
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-ViViD/nodes.py", line 18, in <module>
    from ViViD.src.models.pose_guider import PoseGuider
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-ViViD/ViViD/src/models/pose_guider.py", line 8, in <module>
    from src.models.motion_module import zero_module
ModuleNotFoundError: No module named 'src.models'

2024-10-07 22:41:48,884 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI-ViViD module for custom nodes: No module named 'src.models'
2024-10-07 22:41:49,017 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI/__init__.py", line 5, in <module>
    from .video_synthesis_nodes import DownloadModelsNode, CogVideoNode,TextEncode
  File "/home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI/video_synthesis_nodes.py", line 8, in <module>
    from diffsynth.extensions.RIFE import RIFEInterpolater
  File "/home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI/diffsynth/__init__.py", line 5, in <module>
    from .pipelines import *
  File "/home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI/diffsynth/pipelines/__init__.py", line 1, in <module>
    from .sd_image import SDImagePipeline
  File "/home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI/diffsynth/pipelines/sd_image.py", line 3, in <module>
    from ..controlnets import MultiControlNetManager, ControlNetUnit, ControlNetConfigUnit, Annotator
  File "/home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI/diffsynth/controlnets/__init__.py", line 1, in <module>
    from .controlnet_unit import ControlNetConfigUnit, ControlNetUnit, MultiControlNetManager
  File "/home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI/diffsynth/controlnets/controlnet_unit.py", line 3, in <module>
    from .processors import Processor_id
  File "/home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI/diffsynth/controlnets/processors.py", line 5, in <module>
    from controlnet_aux.processor import (
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/processor.py", line 10, in <module>
    from controlnet_aux import (CannyDetector, ContentShuffleDetector, HEDdetector,
ImportError: cannot import name 'CannyDetector' from 'controlnet_aux' (/home/runner/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/__init__.py)

2024-10-07 22:41:49,017 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/DiffSynth-ComfyUI module for custom nodes: cannot import name 'CannyDetector' from 'controlnet_aux' (/home/runner/ComfyUI/custom_nodes/ComfyUI-Inference-Core-Nodes/src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/__init__.py)
2024-10-07 22:41:49,024 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/FancyVideo-ComfyUI/__init__.py", line 11, in <module>
    from fancyvideo.pipelines.fancyvideo_infer_pipeline import InferPipeline
  File "/home/runner/ComfyUI/custom_nodes/FancyVideo-ComfyUI/fancyvideo/pipelines/fancyvideo_infer_pipeline.py", line 23, in <module>
    from fancyvideo.models.cv_vae.modeling_vae import CVVAEModel
  File "/home/runner/ComfyUI/custom_nodes/FancyVideo-ComfyUI/fancyvideo/models/cv_vae/modeling_vae.py", line 6, in <module>
    from diffusers.modeling_utils import ModelMixin
ModuleNotFoundError: No module named 'diffusers.modeling_utils'

2024-10-07 22:41:49,024 - root - WARNING - Cannot import /home/runner/ComfyUI/custom_nodes/FancyVideo-ComfyUI module for custom nodes: No module named 'diffusers.modeling_utils'
2024-10-07 22:41:49,301 - root - WARNING - Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-OOTDiffusion.Disable/__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-OOTDiffusion.Disable/inference_ootd.py", line 16, in <module>
    from . import pipelines_ootd

**Comment by frankchieng** [comment]
there are two methods this issue can be resolved.First,you can downgrade the diffusers version corresponding to diffusers==0.26.2 in the requirements.txt. Second,if you upgrade diffusers to updated version like 0.30.3, you should modify the code of 
```
        self.check_inputs(
            prompt,
            control_image,
            mask_image,
            height,
            width,
            callback_steps,
            output_type,
            negative_prompt,
            prompt_embeds,
            negative_prompt_embeds,
            controlnet_conditioning_scale,
            control_guidance_start,
            control_guidance_end,
            callback_on_step_end_tensor_inputs,
            padding_mask_crop,
        )
```
located in pipelines/VirtualTryOnPipeline.py as below
``` 
        self.check_inputs(
            prompt,
            control_image,
            mask_image,
            height,
            width,
            callback_steps,
            output_type,
            negative_prompt,
            prompt_embeds,
            negative_prompt_embeds,
            controlnet_conditioning_scale=controlnet_conditioning_scale,
            control_guidance_start=control_guidance_start,
            control_guidance_end=control_guidance_end,
            callback_on_step_end_tensor_inputs=callback_on_step_end_tensor_inputs,
            padding_mask_crop=padding_mask_crop,
        )
```
